import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const kanit = Kanit({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${kanit.variable} antialiased`}>
        <header className="fixed top-0 z-50 w-full bg-white shadow-md">
          <Navbar />
        </header>
        <main className="pt-20">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
