import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Bounce from "@/components/bounce";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { getLocale } from "next-intl/server";

const locales = ["th", "en"];

const kanit = Kanit({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  weight: ["500", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
  if (!locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages();
  console.log("language =", locale);
  console.log(`Loaded ${locale} messages:`, messages);
  return (
    <html lang={locale}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css"
        />
      </head>
      <body className={`${kanit.variable} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <header className="fixed top-0 z-50 w-full shadow-md bg-white">
            <Navbar />
          </header>
          <main className="pt-20">{children}</main>
          <Bounce />
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
