import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Bounce from "@/components/bounce";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

const locales = ["th", "en"];

const kanit = Kanit({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  weight: ["500", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages();
  return (
    <html lang={locale}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css"
        />
      </head>
      <body className={`${kanit.variable} antialiased`}>
        <header
          className="fixed top-0 z-50 w-full shadow-md 
        bg-white"
        >
          <Navbar />
        </header>
        <main className="pt-20">
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </main>
        <Bounce />
        <Footer />
      </body>
    </html>
  );
}
